/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package projetrf.vue;

import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import projetrf.data.RequetesEntreprise;
import projetrf.data.RequetesVille;
import projetrf.model.Ville;

/**
 *
 * @author Travail
 */
public class VueEntreprise extends javax.swing.JFrame {

  
    
    private String Adresse1="";
    private String Adresse2="";
    private String NOM="";
    private int id_ville=0;
    
    
    
    public VueEntreprise() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldEntrepriseNom = new javax.swing.JTextField();
        jTextFieldEntrepriseAdr1 = new javax.swing.JTextField();
        jTextFieldEntrepriseAdr2 = new javax.swing.JTextField();
        jComboBoxEntrepriseVille = new javax.swing.JComboBox();
        JbuttonEntrepriseValide = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldEntrepriseCodePostal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Entreprise");

        jLabel2.setText("Nom");

        jLabel3.setText("Adress1");

        jLabel4.setText("Adress2");

        jLabel5.setText("Ville");

        jComboBoxEntrepriseVille.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxEntrepriseVilleItemStateChanged(evt);
            }
        });

        JbuttonEntrepriseValide.setText("Valide");
        JbuttonEntrepriseValide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JbuttonEntrepriseValideMouseClicked(evt);
            }
        });

        jLabel6.setText("Code postal");

        jTextFieldEntrepriseCodePostal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldEntrepriseCodePostalKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(jLabel1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldEntrepriseAdr1)
                                .addComponent(jTextFieldEntrepriseNom, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTextFieldEntrepriseAdr2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFieldEntrepriseCodePostal, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxEntrepriseVille, 0, 201, Short.MAX_VALUE))
                        .addContainerGap(20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JbuttonEntrepriseValide, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldEntrepriseNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldEntrepriseAdr1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldEntrepriseAdr2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldEntrepriseCodePostal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxEntrepriseVille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(37, 37, 37)
                .addComponent(JbuttonEntrepriseValide)
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JbuttonEntrepriseValideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JbuttonEntrepriseValideMouseClicked
        try {
            Adresse1 = jTextFieldEntrepriseAdr1.getText().toLowerCase();
            Adresse2 = jTextFieldEntrepriseAdr2.getText().toLowerCase();

            NOM = jTextFieldEntrepriseNom.getText().toUpperCase();
            Ville ville = (Ville) this.jComboBoxEntrepriseVille.getSelectedItem();
            id_ville = ville.getIdville();
            

            RequetesEntreprise.insertEntreprise(id_ville, NOM, Adresse1, Adresse2);
        } catch (SQLException ex) {
            Logger.getLogger(VueEntreprise.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_JbuttonEntrepriseValideMouseClicked

    private void jTextFieldEntrepriseCodePostalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEntrepriseCodePostalKeyReleased
     
        
        try {

            List<projetrf.model.Ville> vv1 = RequetesVille.rechercheVilleByCp(jTextFieldEntrepriseCodePostal.getText().trim());

            jComboBoxEntrepriseVille.removeAllItems();
            for (Ville ville : vv1) {
                jComboBoxEntrepriseVille.addItem(ville);

            }

        } catch (SQLException ex) {
            Logger.getLogger(VueVille.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTextFieldEntrepriseCodePostalKeyReleased

    private void jComboBoxEntrepriseVilleItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxEntrepriseVilleItemStateChanged
        
        //  Ville ville = (Ville) this.jComboBoxEntrepriseVille.getSelectedItem();
         // id_ville =ville.getIdville();
    }//GEN-LAST:event_jComboBoxEntrepriseVilleItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VueEntreprise.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VueEntreprise.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VueEntreprise.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VueEntreprise.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new VueEntreprise().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JbuttonEntrepriseValide;
    private javax.swing.JComboBox jComboBoxEntrepriseVille;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextFieldEntrepriseAdr1;
    private javax.swing.JTextField jTextFieldEntrepriseAdr2;
    private javax.swing.JTextField jTextFieldEntrepriseCodePostal;
    private javax.swing.JTextField jTextFieldEntrepriseNom;
    // End of variables declaration//GEN-END:variables
}
