/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package projetrf.vue;

import java.awt.event.ItemEvent;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import projetrf.data.*;
import projetrf.model.*;

/**
 *
 * @author plepelletier
 */
public class VueInterlocuteur extends javax.swing.JFrame {

    /**
     * Creates new form VueInterlocuteur
     */
    public VueInterlocuteur() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabelClient = new javax.swing.JLabel();
        jLabelClientNom = new javax.swing.JLabel();
        jButtonClientAjouter = new javax.swing.JButton();
        jLabelClientPrenom = new javax.swing.JLabel();
        jLabelClientEmail = new javax.swing.JLabel();
        jLabelClientCP = new javax.swing.JLabel();
        jTextFieldClientPrenom = new javax.swing.JTextField();
        jTextFieldClientEmail = new javax.swing.JTextField();
        jTextFieldInterlocuteurCpRecherche = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxInterlocuteurVille = new javax.swing.JComboBox();
        jLabelClientNom1 = new javax.swing.JLabel();
        jTextFieldClientNom = new javax.swing.JTextField();
        jLabelInterlocuteurcommrcial = new javax.swing.JLabel();
        jComboBoxInterlocuteurCommercial = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxInterlocuteurService = new javax.swing.JComboBox();
        jComboBoxInterlocuteurEntreprise = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jButtonInterlocuteurCreationCom = new javax.swing.JButton();
        jButtonInterlocuteurCreationEntr = new javax.swing.JButton();
        jButtonInterlocuteurCreationService = new javax.swing.JButton();

        jLabel4.setText("jLabel4");

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabelClient.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelClient.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelClient.setText("Interlocuteur");

        jLabelClientNom.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabelClientNom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelClientNom.setText("Création Interlocuteur");

        jButtonClientAjouter.setText("Ajouter");
        jButtonClientAjouter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonClientAjouterMouseClicked(evt);
            }
        });
        jButtonClientAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClientAjouterActionPerformed(evt);
            }
        });

        jLabelClientPrenom.setText("Prénom");

        jLabelClientEmail.setText("Email : ");

        jLabelClientCP.setText(" Code Postal");

        jTextFieldInterlocuteurCpRecherche.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldInterlocuteurCpRechercheKeyReleased(evt);
            }
        });

        jLabel1.setText("Ville : ");

        jComboBoxInterlocuteurVille.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxInterlocuteurVilleItemStateChanged(evt);
            }
        });

        jLabelClientNom1.setText("Nom");

        jLabelInterlocuteurcommrcial.setText("Commercial");

        jComboBoxInterlocuteurCommercial.setPreferredSize(new java.awt.Dimension(28, 30));

        jLabel2.setText("Service");

        jComboBoxInterlocuteurService.setPreferredSize(new java.awt.Dimension(28, 30));

        jLabel3.setText("Entreprise");

        jButtonInterlocuteurCreationCom.setText("Creation");

        jButtonInterlocuteurCreationEntr.setText("Creation");

        jButtonInterlocuteurCreationService.setText("Création");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelClient, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelClientNom1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelClientPrenom)
                            .addComponent(jLabelClientEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldClientPrenom, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldClientNom, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldClientEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelClientNom, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabelInterlocuteurcommrcial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(68, 68, 68)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jComboBoxInterlocuteurEntreprise, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBoxInterlocuteurCommercial, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBoxInterlocuteurService, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(75, 75, 75)
                                    .addComponent(jButtonClientAjouter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGap(86, 86, 86)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButtonInterlocuteurCreationCom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonInterlocuteurCreationEntr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonInterlocuteurCreationService)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabelClientCP)
                            .addGap(26, 26, 26)
                            .addComponent(jTextFieldInterlocuteurCpRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(23, 23, 23)
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jComboBoxInterlocuteurVille, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(45, 45, 45))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jComboBoxInterlocuteurCommercial, jComboBoxInterlocuteurEntreprise, jComboBoxInterlocuteurService});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabelClient)
                .addGap(38, 38, 38)
                .addComponent(jLabelClientNom)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelClientNom1)
                    .addComponent(jTextFieldClientNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelClientPrenom)
                    .addComponent(jTextFieldClientPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelClientEmail)
                    .addComponent(jTextFieldClientEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelClientCP)
                    .addComponent(jTextFieldInterlocuteurCpRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxInterlocuteurVille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxInterlocuteurCommercial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelInterlocuteurcommrcial, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonInterlocuteurCreationCom))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxInterlocuteurEntreprise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jButtonInterlocuteurCreationEntr))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxInterlocuteurService, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jButtonInterlocuteurCreationService))
                .addGap(45, 45, 45)
                .addComponent(jButtonClientAjouter)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jComboBoxInterlocuteurCommercial, jComboBoxInterlocuteurEntreprise, jComboBoxInterlocuteurService});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonClientAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClientAjouterActionPerformed

    }//GEN-LAST:event_jButtonClientAjouterActionPerformed

    private void jButtonClientAjouterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonClientAjouterMouseClicked
       
        
        String nom= jTextFieldClientNom.getText();
        String prenom= jTextFieldClientPrenom.getText();
        String email= jTextFieldClientEmail.getText();
        Ville ville= (Ville) jComboBoxInterlocuteurVille.getSelectedItem();
         Commercial commercial= (Commercial) jComboBoxInterlocuteurCommercial.getSelectedItem();
           Service service= (Service) jComboBoxInterlocuteurService.getSelectedItem();
         
        int id_ville=ville.getIdville();
        int id_commercial =commercial.getIdCommercial();
        int id_service =service.getIdservice();
        try {
            RequetesInterlocuteur.insertInterlocuteur(id_commercial, id_ville, id_service, nom, prenom, email);
         
            
        } catch (SQLException ex) {
            Logger.getLogger(VueInterlocuteur.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Mise à jour interlocuteur "," Erreur ", JOptionPane.ERROR_MESSAGE);
        }
        
        
        
    }//GEN-LAST:event_jButtonClientAjouterMouseClicked

    private void jTextFieldInterlocuteurCpRechercheKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldInterlocuteurCpRechercheKeyReleased
        
       
        try {
            List<projetrf.model.Ville> vv1 = RequetesVille.rechercheVilleByCp(jTextFieldInterlocuteurCpRecherche.getText().trim());

                jComboBoxInterlocuteurVille.removeAllItems();
                for (Ville ville : vv1) {
                    jComboBoxInterlocuteurVille.addItem(ville);
                }
        } catch (SQLException ex) {
            Logger.getLogger(VueInterlocuteur.class.getName()).log(Level.SEVERE, null, ex);
       
        }
    }//GEN-LAST:event_jTextFieldInterlocuteurCpRechercheKeyReleased

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        try {
                List<Commercial> pp1 = RequetesCommercial.selectCommercial();
                for (Commercial commercial : pp1) {

                    jComboBoxInterlocuteurCommercial.addItem(commercial);
                }
            } catch (SQLException ex) {
                Logger.getLogger(VueInterlocuteur.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        try {
            

            List< Entreprise> ee = RequetesEntreprise.selectEntreprise();
            for (Entreprise entreprise : ee) {
                jComboBoxInterlocuteurEntreprise.addItem(entreprise);
            }
        } catch (SQLException ex) {
            Logger.getLogger(VueInterlocuteur.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
                List<Service> ss1 = RequetesService.selectService();
                for (Service service : ss1) {

                    jComboBoxInterlocuteurService.addItem(service);
                }
            } catch (SQLException ex) {
                Logger.getLogger(VueInterlocuteur.class.getName()).log(Level.SEVERE, null, ex);
            }
        
    }//GEN-LAST:event_formWindowOpened

    private void jComboBoxInterlocuteurVilleItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxInterlocuteurVilleItemStateChanged
        jComboBoxInterlocuteurVille.getSelectedItem();
    }//GEN-LAST:event_jComboBoxInterlocuteurVilleItemStateChanged

    
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VueInterlocuteur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VueInterlocuteur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VueInterlocuteur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VueInterlocuteur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new VueInterlocuteur().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClientAjouter;
    private javax.swing.JButton jButtonInterlocuteurCreationCom;
    private javax.swing.JButton jButtonInterlocuteurCreationEntr;
    private javax.swing.JButton jButtonInterlocuteurCreationService;
    private javax.swing.JComboBox jComboBoxInterlocuteurCommercial;
    private javax.swing.JComboBox jComboBoxInterlocuteurEntreprise;
    private javax.swing.JComboBox jComboBoxInterlocuteurService;
    private javax.swing.JComboBox jComboBoxInterlocuteurVille;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelClient;
    private javax.swing.JLabel jLabelClientCP;
    private javax.swing.JLabel jLabelClientEmail;
    private javax.swing.JLabel jLabelClientNom;
    private javax.swing.JLabel jLabelClientNom1;
    private javax.swing.JLabel jLabelClientPrenom;
    private javax.swing.JLabel jLabelInterlocuteurcommrcial;
    private javax.swing.JTextField jTextFieldClientEmail;
    private javax.swing.JTextField jTextFieldClientNom;
    private javax.swing.JTextField jTextFieldClientPrenom;
    private javax.swing.JTextField jTextFieldInterlocuteurCpRecherche;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
