/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package projetrf.vue;

import java.awt.Component;
import java.sql.SQLException;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.SQLException;
import java.util.logging.Logger;
import projetrf.data.RequetesPays;
import projetrf.data.RequetesVille;
import projetrf.model.Pays;
import projetrf.model.Ville;

/**
 *
 * @author Travail
 */
public class VueVilleModifie extends javax.swing.JFrame {

    /**
     * Creates new form VueVilleModifie
     */
    public VueVilleModifie() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButtonModifieVilleValide = new javax.swing.JButton();
        jLabelModifieVilleNom = new javax.swing.JLabel();
        jLabelModifieVilleCodePostal = new javax.swing.JLabel();
        jTextFieldModiefieVilleNom = new javax.swing.JTextField();
        jComboBoxModifieVillePays = new javax.swing.JComboBox();
        jTextFieldModifieVilleCodePostal = new javax.swing.JTextField();
        jLabelModifieVillePays = new javax.swing.JLabel();
        jLabelModifieVille = new javax.swing.JLabel();
        jComboBoxModifieVilleList = new javax.swing.JComboBox();

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jButtonModifieVilleValide.setText("Valide");
        jButtonModifieVilleValide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModifieVilleValideActionPerformed(evt);
            }
        });

        jLabelModifieVilleNom.setText("Nom");

        jLabelModifieVilleCodePostal.setText("Code Postal");

        jTextFieldModiefieVilleNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldModiefieVilleNomActionPerformed(evt);
            }
        });
        jTextFieldModiefieVilleNom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldModiefieVilleNomKeyPressed(evt);
            }
        });

        jComboBoxModifieVillePays.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxModifieVillePays.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxModifieVillePaysActionPerformed(evt);
            }
        });

        jLabelModifieVillePays.setText("Ville");

        jLabelModifieVille.setText("Modification Ville");

        jComboBoxModifieVilleList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxModifieVilleListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonModifieVilleValide)
                .addGap(59, 59, 59))
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelModifieVilleNom)
                    .addComponent(jLabelModifieVilleCodePostal)
                    .addComponent(jLabelModifieVillePays))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldModiefieVilleNom)
                    .addComponent(jLabelModifieVille, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxModifieVilleList, 0, 140, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextFieldModifieVilleCodePostal, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBoxModifieVillePays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelModifieVille, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldModiefieVilleNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelModifieVilleNom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxModifieVilleList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelModifieVilleCodePostal)
                    .addComponent(jTextFieldModifieVilleCodePostal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxModifieVillePays, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelModifieVillePays, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(22, 22, 22)
                .addComponent(jButtonModifieVilleValide)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxModifieVillePaysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxModifieVillePaysActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxModifieVillePaysActionPerformed

    private void jButtonModifieVilleValideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModifieVilleValideActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonModifieVilleValideActionPerformed

    private void jComboBoxModifieVilleListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxModifieVilleListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxModifieVilleListActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       
     
       
         
         
    }//GEN-LAST:event_formWindowOpened

    private void jTextFieldModiefieVilleNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldModiefieVilleNomActionPerformed
        
       
        
    }//GEN-LAST:event_jTextFieldModiefieVilleNomActionPerformed

    private void jTextFieldModiefieVilleNomKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldModiefieVilleNomKeyPressed
        try {
          
            List<projetrf.model.Ville> vv1 = RequetesVille.selectVilleByName(jTextFieldModiefieVilleNom.getText());
            System.out.println(vv1.toString());
            jComboBoxModifieVilleList.removeAllItems();
            for (Ville ville : vv1) {               
                jComboBoxModifieVilleList.addItem(ville);
               
            }


        } catch (SQLException ex) {
            Logger.getLogger(VueVille.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTextFieldModiefieVilleNomKeyPressed


    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new VueVilleModifie().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonModifieVilleValide;
    private javax.swing.JComboBox jComboBoxModifieVilleList;
    private javax.swing.JComboBox jComboBoxModifieVillePays;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabelModifieVille;
    private javax.swing.JLabel jLabelModifieVilleCodePostal;
    private javax.swing.JLabel jLabelModifieVilleNom;
    private javax.swing.JLabel jLabelModifieVillePays;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldModiefieVilleNom;
    private javax.swing.JTextField jTextFieldModifieVilleCodePostal;
    // End of variables declaration//GEN-END:variables
}
